DROP TABLE  conduit_db."ARTICLES",
            conduit_db."ARTICLES_EDITS",
            conduit_db."ARTICLES_STATUS",
            conduit_db."ATTRIBUTES",
            conduit_db."BOOKS_STATUS",
            conduit_db."BOOKS",
            conduit_db."COMMENTS",
            conduit_db."IMAGES_STATUS",
            conduit_db."IMAGES",
            conduit_db."TAGS",
            conduit_db."TEAMS",
            conduit_db."USERS"